name: CI - Ahorcado

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile check (syntax only)
        run: python -m py_compile ahorcado.py

      - name: Start Flask app in background
        run: |
          export TEST_SECRET=${{ secrets.TEST_SECRET }}
          nohup python app.py > flask.log 2>&1 &
          for i in {1..10}; do
            echo "Esperando que Flask esté disponible..."
            curl -s http://localhost:5000 && break
            sleep 2
          done
          echo "Servidor Flask iniciado"

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

      - name: Run unit tests with coverage
        run: python -m coverage run -m unittest discover -s tests

      - name: Show coverage report
        run: python -m coverage report -m

      - name: Generate coverage XML
        run: python -m coverage xml

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage xml -o coverage-report.xml

      - name: Run acceptance tests
        run: |
          behave features

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report.xml
