name: CI - Ahorcado

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: 1234

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile check (syntax only)
        run: python -m py_compile ahorcado.py

      - name: Start web server
        run: |
          nohup python web/app.py > flask.log 2>&1 &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            echo "Esperando que Flask esté disponible..."
            curl -s http://localhost:5000 && break
            sleep 2
          done
          echo "Servidor Flask iniciado"

      - name: Extra wait for Flask to fully initialize
        run: sleep 5

      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage report -m
          coverage xml -o coverage-report.xml

      - name: Run acceptance tests
        run: behave features

      - name: Show server logs if failed
        if: failure()
        run: cat flask.log || true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report.xml
